export default function Features() {
  return (
    <section className="space-y-8 pb-12">
      <div className="rounded-[2rem] border border-slate-700 bg-[#07101f]/90 p-10 shadow-glow">
        <h2 className="text-3xl font-semibold text-white">Core Features</h2>
        <p className="mt-4 max-w-3xl text-slate-300">
          This project covers the most important cybersecurity concepts for a college or internship portfolio while remaining easy to follow and customize.
        </p>
      </div>
      <div className="grid gap-6 lg:grid-cols-2">
        {[
          { title: 'Regex-based Detection', details: 'Flag common SQL injection vectors like OR 1=1, UNION SELECT, DROP TABLE, and more.' },
          { title: 'Simulated AI Scoring', details: 'Confidence values generated by code to simulate how an ML model could be integrated later.' },
          { title: 'JWT Authentication', details: 'Secure auth with token-based sessions and protected backend routes.' },
          { title: 'Attack Monitoring', details: 'Review logs, filter by severity, and manage suspicious IPs from the admin view.' },
        ].map((feature) => (
          <div key={feature.title} className="card-panel rounded-3xl p-6">
            <h3 className="text-xl font-semibold text-white">{feature.title}</h3>
            <p className="mt-3 text-slate-400">{feature.details}</p>
          </div>
        ))}
      </div>
    </section>
  );
}
